# Generated by Django 3.0.5 on 2020-04-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestions',
            fields=[
                ('gameQuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('roundNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('gameID', models.AutoField(primary_key=True, serialize=False)),
                ('numberOfRounds', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('realName', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('numberOfPicks', models.IntegerField()),
                ('points', models.IntegerField()),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Games')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('voteID', models.AutoField(primary_key=True, serialize=False)),
                ('gameQuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.GameQuestions')),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerID_FK', to='API.Players')),
                ('voterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voterID_FK', to='API.Players')),
            ],
        ),
        migrations.AddField(
            model_name='gamequestions',
            name='gameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Games'),
        ),
        migrations.AddField(
            model_name='gamequestions',
            name='playerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Players'),
        ),
        migrations.AddField(
            model_name='gamequestions',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Questions'),
        ),
    ]
