# Generated by Django 3.0.5 on 2020-04-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorrectPigments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='status',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
